version: '3'

services:

  reverse-proxy:
    image: traefik:v2.0
    container_name: "traefik"
    command: 
#     - "--log.level=DEBUG"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"

  miniflux:
    image: miniflux/miniflux:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.miniflux.rule=Host(`miniflux.${DOMAIN}`)"
      - "traefik.http.routers.miniflux.entrypoints=websecure"
      - "traefik.http.routers.miniflux.tls.certresolver=mytlschallenge"
      # Redirect HTTP to HTTPS  
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"


  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - miniflux-db:/var/lib/postgresql/data
 
    #  wp_db:
    #    image: mysql:5.7
    #    volumes:
    #      - db_data:/var/lib/mysql
    #    restart: always
    #    environment:
    #      MYSQL_ROOT_PASSWORD: kjdnwjdmqwldmqwdq5?6789dqhwbdkwqjd
    #      MYSQL_DATABASE: wordpress_database
    #      MYSQL_USER: user65789dwmjkqnddq
    #      MYSQL_PASSWORD: qwmnd67890qwdqwdqwdqh!n

    #  wordpress:
    #    depends_on:
    #      - db
    #    image: wordpress:latest
    #    ports:
    #      - "8000:80"
    #    restart: always
    #    environment:
    #      WORDPRESS_DB_HOST: wp_db:3306
    #      WORDPRESS_DB_USER: user65789dwmjkqnddq
    #      WORDPRESS_DB_PASSWORD: qwmnd67890qwdqwdqwdqh!n
    #      WORDPRESS_DB_NAME: wordpress_database
    #    labels:
    #      - "traefik.enable=true"
    #      - "traefik.http.routers.cooking.rule=Host(`cooking.${DOMAIN}`)"
    #      - "traefik.http.routers.cooking.entrypoints=websecure"
    #      - "traefik.http.routers.cooking.tls.certresolver=mytlschallenge"
    #      # Redirect HTTP to HTTPS  
    #      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"

  bitwardenrs:
    container_name: bitwardenrs
    image: bitwardenrs/server:latest
    volumes:
      - ./bw-data/:/data/
    environment:
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pass.rule=Host(`pass.${DOMAIN}`)"
      - "traefik.http.routers.pass.entrypoints=websecure"
      - "traefik.http.routers.pass.tls.certresolver=mytlschallenge"
      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"




volumes:
  miniflux-db:
  db_data: {}

